### ISSUE TITLE
[Enhancement] Add support for housing lottery timers

### ISSUE THREAD

**Issue by ladybunne** [Xenoveritas/js-timer#9]
Hi there! With the release of Patch 6.1, there doesn't appear to be support in-game for viewing when a housing lottery period will end, without going to a placard. I figured it'd be a great feature to add to the site, since I'm sure people would come to it, looking to see how long is left in a lottery period.

Please disregard if feature requests are unwelcome. Thank you for your time, and the site!

**Comment by Xenoveritas** [comment]
Well, now that housing lotteries are *hopefully* on a consistent pace again, I can look into adding this.

**Comment by Xenoveritas** [comment]
This is now implemented, the housing lottery phase is now at the bottom.
